# -*- coding: utf-8 -*-
"""Ai lab 4-BSAI-044.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zazkz6DkHEeCD-q1S_Af03E5aH2yMPa5
"""

import string
def luhn_algorithm(card_number):
  chk_dgt=int(card_number[-1])
  digits= [int(x) for x in card_number[:-1]]

  digits.reverse()

  for i in range(len(digits)):
    if i%2 == 0:
      digits[i]*=2
      if digits[i]>9:
        digits[i]-=9
  total_sum = sum(digits) + chk_dgt
  return total_sum%10==0
card_number = input("enter card number:")
if luhn_algorithm(card_number):
  print("card number is valid")
else:
  print("crad number is not valid")
def rmv_pncts(string):
  punc=string.punctuation
  result = ''.join(char for char in string if char not in punc)
  return result
  string=input("enter string:")
  print(rmv_pncts(strings))
def sort(lst):
  words=lst.split()
  n = len(words)
  for i in range(n):
    for j in range(0, n-i-1):
      if words[j]>words[j+1]:
        words[j], words[j+1], words[j]
  return ''.join(words)
text=input("enter text:")
sort_text=sort(text)
print(sort_text)